build:
  nodes:
    coverage:
      tests:
        override:
        - command: 'vendor/bin/phpunit --coverage-clover=./log/coverage.xml'
          coverage:
            file: './log/coverage.xml'
            format: 'clover'
    tests:
      dependencies:
        before:
        # The following installs the most recent MODX CMS version, you might want
        # to install a specific release tag or branch instead.
        - git clone --depth=1 https://github.com/modxcms/revolution
        # - git checkout tags/v2.6.5-pl
        - php -r "file_exists('revolution/_build/build.properties.php') || copy('revolution/_build/build.properties.sample.php', 'revolution/_build/build.properties.php');"
        - php -r "file_exists('revolution/_build/build.config.php') || copy('revolution/_build/build.config.sample.php', 'revolution/_build/build.config.php');"
        - php revolution/_build/transport.core.php
        # - php ./index.php --installmode=new
        - php ./tests/scrutinizer/setup.php
        - mkdir temp
        - mkdir temp/database
        - cp -r tests/database/ temp/database/
  # MySQL https://scrutinizer-ci.com/docs/build/mysql_credentials

filter:
  dependency_paths:
  - revolution/*
  excluded_paths:
  - tests/*
  # this file just has every MODX setting as a method, maybe at a future point it could be refactored
  - src/Blendable/SystemSetting.php