<?php  return array (
  //'id' => 499,
  'type' => 'document',
  'contentType' => 'text/html',
  'pagetitle' => 'Blend Resource Test 4',
  'longtitle' => '',
  'description' => '',
  'alias' => 'test-blend-many-resource-4',
  'link_attributes' => '',
  'published' => false,
  'pub_date' => 0,
  'unpub_date' => 0,
  'parent' => 0,
  'isfolder' => false,
  'introtext' => NULL,
  'content' => 'Content #4 goes here',
  'richtext' => true,
  'template' => '',
  'menuindex' => 0,
  'searchable' => true,
  'cacheable' => true,
  'createdby' => 0,
  //'createdon' => '2018-01-18 15:06:43',
  'editedby' => 0,
  'editedon' => 0,
  'deleted' => false,
  'deletedon' => 0,
  'deletedby' => 0,
  'publishedon' => 0,
  'publishedby' => 0,
  'menutitle' => '',
  'donthit' => false,
  'privateweb' => false,
  'privatemgr' => false,
  'content_dispo' => 0,
  'hidemenu' => false,
  'class_key' => 'modDocument',
  'context_key' => 'web',
  'content_type' => 1,
  'uri' => NULL,
  'uri_override' => 0,
  'hide_children_in_tree' => 0,
  'show_in_tree' => 1,
  'properties' => NULL,
  'tv' => 
  array (
  ),
  'resource_groups' =>
  array (
  ),
  'extras' => 
  array (
  ),
);
